config/routes.rb
Blog::Application.routes.draw do
  
  resources :tags

  resources :comments

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "entries/index"

  match "/entries/all" => "entries#entry_list"
  match "/tag/tag_id" => "entries#show_by_tag"

  resources :entries

  root :to => 'entries#index', :as => 'store'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :body, :date, :tag, :title
  has_many :comments, :dependent => :destroy
  has_many :taggings, :dependent => :destroy
  has_many :tags, :through => :taggings
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  skip_before_filter :authorize, :only => [:index, :show]
  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.find(:all, :order => 'created_at DESC')
    @show_comments = TRUE

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entries }
    end
  end

  def entry_list
    @entries = Entry.find(:all, :order => 'created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])
    @comment = Comment.new(:entry => @entry )
    @show_comments = FALSE


    @tags = @entry.tag.split(/,/)
    @tags.each do |tag| 
      @t = Tag.find_or_create_by_body(tag.strip)
      @t.save
 
      @tagging = Tagging.find_or_create_by_entry_id_and_tag_id(:entry_id => @entry.id, :tag_id => @t.id)
      @tagging.save
    end  
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entry }
    end
  end

  def show_by_tag
    @entries = Entry.find_by_tag(params[:tag], :order => 'created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entries }
    end
  end


  # GET /entries/new
  # GET /entries/new.json
  def new
    @entry = Entry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(params[:entry])

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render json: @entry, status: :created, location: @entry }
      else
        format.html { render action: "new" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    @entry = Entry.find(params[:id])

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_comment.html.erb
<div id="comment">
  <i><h4><%=h comment.name %> says:</h4></i>  
  <% if session[:user_id] %>    
    <%= link_to image_tag("delete.png", :border => 0, :title => "Delete"), comment, :method => :delete, data: { confirm: 'Are you sure?' }  %>          
  <% end %>
  
  <div id="comment_text">
    <%= simple_format h(comment.body) %>
  </div>
  
</div>

app/views/entries/_entry.html.erb
<div id="entry">
  <div class="date"><%= entry.date %></div>
  <h2><b><%= link_to entry.title, entry %></b></h2>
  
  <%= entry.body.html_safe %>      
  <br /><br />
  
  <% if entry.tags.count > 0 %>
    <b>Tags:</b>
    <% entry.tags.each do |tag| %>
      <%= link_to tag.body, tag %>      
    <% end %>
  <% end %>  

  <% if @show_comments %>
    <div class="comment_link">
      <% if entry.comments.count > 0 %>
        <%= link_to "Comments: #{entry.comments.count}", entry %>           
      <% end %>
    </div>
  <% end %>
</div>
<br />

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<br /><br />
  <div class="field">    
    <%= f.text_field :title, :size => 105, :placeholder => "Title" %>
  </div>
  <div class="field">    
    <%= f.text_area :body, :rows => 10, :cols => 80, :placeholder => "Entry text" %>
  </div>
  <div class="field">
    <%= f.text_area :tag, :rows => 1, :cols => 80, :placeholder => "Tags" %>
  </div>
  <div class="field">    
    <%= f.date_select :date %>
  </div>  
  <div class="submit_berry">
    <%= image_submit_tag("el.png") %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/entry_list.html.erb
<div id="entry_list">
  <table>
    <% @entries.each do |entry| %>
      <tr> 
        <td width=70%>
          <h3><b><%= link_to entry.title, entry %></b></h3>
        </td>

        <td>      
          <p class="date"><%= entry.date %></p>
        </td>

        <td>
          <%= link_to image_tag("el.png", :border => 0, :title => "Edit"), edit_entry_path(entry) %>              
        </td>      

        <td>
          <%= link_to image_tag("np.png", :border => 0, :title => "Delete"), entry, :method => :delete, data: { confirm: 'Are you sure?' }  %>          
        </td>       
        
      </tr>
    <% end %>
  </table>
</div>

app/views/entries/index.html.erb
<div id="entry_options">
	<% if session[:user_id] %>
	  	<%= link_to image_tag("np.png", :border => 0, :title => "New entry"), new_entry_path %>
	  	<%= link_to image_tag("el.png", :border => 0, :title => "Entry list"), '/entries/all' %>
	  	<%= link_to image_tag("se.png", :border => 0, :title => "Some another option"), login_path, :method => :create %>
  <% end %>	
</div>
<br /><br />
<table>	
	<% @entries.each do |entry| %>
	  <tr><%= render entry %></tr>
<% end %>
</table>

<br />

app/views/entries/new.html.erb
<div id="post_form">
	<%= render 'form' %>
</div>
<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<%= render @entry %>

<%= render :partial => 'comment', :collection => @entry.comments %>

<hr />
<div id="post_form">
	<%= form_for @comment do |c| %>  
		<div class="field">  	  
		  <%= c.text_field :name, :size=> 35, :placeholder => "Name" %>	  		
		  <%= c.text_field :email, :size => 35, :placeholder => "Email" %>	  
		</div>

		<div class="field">  
		  <%= c.text_area :body,  :rows => 10, :cols => 59, :placeholder => "Comment" %>	  
		</div>

		<div class="field">  
		  <%= c.submit "Post Comment" %>	  
		</div>

		<%= c.hidden_field :entry_id, value: @entry.id %>	  		
	<% end %>
</div>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>