config/routes.rb
Blog::Application.routes.draw do
  
  resources :tags

  resources :comments

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "entries/index"

  match "/entries/all" => "entries#entry_list"
  match "/tag/tag_id" => "entries#show_by_tag"

  resources :entries

  root :to => 'entries#index', :as => 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yekaterina Zhmud</title>  
  <link href="http://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet" type="text/css">

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="main">		
	  <div id="banner">
	  <% if session[:user_id] %>          
      <font><%= @page_title || "Your shiny blog" %></font>
    <% else %>
      <font><%= @page_title || "My shiny blog" %></font>
    <% end %>
    </div>
  
    <div id="columns">
      <div id="links">
      	<table align=left>
      		<tr>
      			<td width=7%>
      				<a href="/entries">Home</a>
      			</td>
      			<td width=7%>
      			  <a href="/shop">Shop</a>
      			</td>
      			<td width=7%>
      			  <a href="/about">About</a>
      			</td>
      			<td width=10%>
      			  <a href="/contact">Contact</a>
      			</td>
      			<td width=69%>   		    			
      			</td>      		
      		</tr>
      	</table>
      </div><br />
      <div id="content">
        <%= yield %>
      </div>    
    </div><br /><br />
    <div id="ft">      
      <% if session[:user_id] %>
      	<%= link_to image_tag("logout.png", :border => 0), logout_path, :method => :delete %>
      <% else %>
        <%= link_to image_tag("login.png", :border => 0), login_path, :method => :create %>
	    <% end %>	
	    Yekaterina Zhmud, 2013	  
    </div>
  </div>
</body>
</html>